### ISSUE TITLE
error in recovery of 2of3 account

### ISSUE THREAD

**Issue by baskeman** [greenaddress/garecovery#21]
I get the following error message when I run the tool:

Traceback (most recent call last):
  File "/usr/local/bin/garecovery-cli", line 7, in <module>
    sys.exit(recoverycli.main(sys.argv))
  File "/usr/local/lib/python2.7/dist-packages/garecovery/recoverycli.py", line 107, in main
    txs = recovery.get_transactions()
  File "/usr/local/lib/python2.7/dist-packages/garecovery/two_of_three.py", line 437, in get_transactions
    clargs.args.search_subaccounts or 0)
  File "/usr/local/lib/python2.7/dist-packages/garecovery/two_of_three.py", line 417, in rescan
    next_utxos = self.get_utxos(subaccounts, pointers)
  File "/usr/local/lib/python2.7/dist-packages/garecovery/two_of_three.py", line 406, in get_utxos
    return self.scan_blockchain(keysets)
  File "/usr/local/lib/python2.7/dist-packages/garecovery/two_of_three.py", line 314, in scan_blockchain
    core = bitcoincore.Connection(clargs.args)
  File "/usr/local/lib/python2.7/dist-packages/garecovery/bitcoincore.py", line 114, in __init__
    http_auth_header = Connection.get_http_auth_header(config, testnet)
  File "/usr/local/lib/python2.7/dist-packages/garecovery/bitcoincore.py", line 77, in get_http_auth_header
    auth_data = open(rpccookiefile, "r").read().strip().encode("ascii")
IOError: [Errno 2] No such file or directory: '/home/btc/.bitcoin/testnet3/.cookie'

I have a full node running with the bitcoin blockchain synched. From the error message it looks like the testnet3 blockchain should be synched...?

**Comment by jkauffman1** [comment]
It looks like the tool is running in testnet mode, which it determines for 20f3 from the destination address. Are you specifying a testnet address?

**Comment by baskeman** [comment]
Not what I know. I use my btc.com wallet and generate a receiving address in the interface. I managed to recover BCH from another wallet using a btc.com tool so the wallet is functional. Its possible to generate both a legacy format address but also a newer format. I've tried both variants but get the same result...

**Comment by greenaddress** [comment]
hi @baskeman 

the recovery tool is designed only for Bitcoin mainnet and testnet not for bch. it won't work with BCH legacy or not.

if you are using a bch tool fork of this tool we invite you to raise an issue directly with the repo of said tool

thank you
