### ISSUE TITLE
Crash when recovering 2of2 wallet

### ISSUE THREAD

**Issue by winchip2** [greenaddress/garecovery#44]
Ran garecovery-cli as shown in the example to recover 2of2 CSV wallet.

Said only  "WARNING:root:This step may take 10 minutes or more" for about an hour then displayed the following. OS is Ubuntu 20.04.3 LTS with a freshly made Bitcoin Core full node with only a single wallet, which is active.

`$ garecovery-cli 2of2-csv -o garecoverie.csv
mnemonic/hex seed: [Redacted]
WARNING:root:This step may take 10 minutes or more
Traceback (most recent call last):
  File "/home/[USERNAME]/Downloads/garecovery-master/venv/bin/garecovery-cli", line 7, in <module>
    sys.exit(recoverycli.main(sys.argv))
  File "/home/[USERNAME]/Downloads/garecovery-master/venv/lib/python3.8/site-packages/garecovery/recoverycli.py", line 98, in main
    txs = recovery.get_transactions()
  File "/home/[USERNAME]/Downloads/garecovery-master/venv/lib/python3.8/site-packages/garecovery/two_of_two_csv.py", line 198, in get_transactions
    utxos = self.scan_subaccount(subaccount_pointer, clargs.args.key_search_depth)
  File "/home/[USERNAME]/Downloads/garecovery-master/venv/lib/python3.8/site-packages/garecovery/two_of_two_csv.py", line 94, in scan_subaccount
    new_utxos = self.get_utxos(outputs)
  File "/home/[USERNAME]/Downloads/garecovery-master/venv/lib/python3.8/site-packages/garecovery/two_of_two_csv.py", line 55, in get_utxos
    result = core.importmulti(requests)
  File "/home/[USERNAME]/Downloads/garecovery-master/venv/lib/python3.8/site-packages/bitcoinrpc/authproxy.py", line 139, in __call__
    response = self._get_response()
  File "/home/[USERNAME]/Downloads/garecovery-master/venv/lib/python3.8/site-packages/bitcoinrpc/authproxy.py", line 179, in _get_response
    http_response = self.__conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1344, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out
`

Not sure what the issue is here.

**Comment by winchip2** [comment]
As a separate issue, it'd be nice to have a way to test if everything works without typing in the mnemonic every time.

**Comment by LeoComandini** [comment]
> It runs for about an hour and then crashes with the following.
> ...
> `socket.timeout: timed out`

Hi @winchip2 , sorry to hear you have issues. Can you please try with
```
$ garecovery-cli 2of2-csv -o garecovery.csv --ignore-mempool
```

With that flag set the tools uses [`scantxoutset`](https://bitcoincore.org/en/doc/0.21.0/rpc/blockchain/scantxoutset/), instead of `importmulti` to look for unspent outputs belonging to the wallet being recovered. It ignores _spent_ outputs the wallet owned, and ignores (and won't recover) unconfirmed outputs (in mempool). It's much faster, so it could be a good compromise for you. If you have unconfirmed outputs, you can recover them running the tool again with `--ignore-mempool` once those outputs will be confirmed.

**Comment by winchip2** [comment]
> > It runs for about an hour and then crashes with the following.
> > ...
> > `socket.timeout: timed out`
> 
> Hi @winchip2 , sorry to hear you have issues. Can you please try with
> 
> ```
> $ garecovery-cli 2of2-csv -o garecovery.csv --ignore-mempool
> ```
> 
> With `--ignore-mempool` the tools uses [`scantxoutset`](https://bitcoincore.org/en/doc/0.21.0/rpc/blockchain/scantxoutset/), instead of `importmulti` to look for unspent outputs belonging to the wallet being recovered. It ignores _spent_ outputs the wallet owned, and ignores (and won't recover) unconfirmed outputs (in mempool). It's much faster, so it could be a good compromise for you. If you have unconfirmed outputs, you can recover them running the tool again with `--ignore-mempool` once those outputs will be confirmed.

Thank you for the reply!

I ran the command as stated.  It asked for my mnemonic, ran about 10 minutes and then stopped without any output to the console.

The csv file only contains the following line:
`tx id,lock time,total out,destination address,coin value,raw tx`

I can still access my Green wallet from a phone, so I see everything's there, and it seems as though all the transactions on this wallet are post-nLockTime so as far as I understand it _should_ be able to run successfully with the option 2of2-csv. I did double check that i have a 2of2 account and not a 2of3 by the way.

**Comment by LeoComandini** [comment]
> The csv file only contains the following line:
> `tx id,lock time,total out,destination address,coin value,raw tx`
> ...
> all the transactions on this wallet are post-nLockTime so as far as I understand it should be able to run successfully with the option 2of2-csv.

To spend your outputs without Green 2FA, you also need to wait for some blocks (~12 months by default) to spend those, more details [here](https://blog.blockstream.com/en-blockstream-green-bitcoin-wallets-now-using-checksequenceverify-timelocks/).

The empty file suggests that your outputs may not be expired yet.
To confirm that you can run the tool with the verbose option 
```
garecovery-cli 2of2-csv -o garecovery.csv --ignore-mempool -v
```
It prints a more verbose output, and if you must wait more blocks to spend those coins, then it will include some lines such as `"Skipping utxo ({TXID}:{VOUT}) not expired ({N} blocks left)"`.
