### ISSUE TITLE
Index error: list index out of range

### ISSUE THREAD

**Issue by lewixlabs** [greenaddress/garecovery#9]
Hi,
after reading & following your guideline, with command
`garecovery-cli 2of2 --nlocktime-file nlocktimes.zip -o garecovery.csv`
i get this error

> Traceback (most recent call last):
  File "/home/ubuntu/venv/bin/garecovery-cli", line 7, in <module>
    sys.exit(recoverycli.main(sys.argv))
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/garecovery/recoverycli.py", line 101, in main
    recovery = get_recovery(clargs.args, mnemonic, seed)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/garecovery/recoverycli.py", line 79, in get_recovery
    return TwoOfTwo(mnemonic, seed, options.nlocktime_file)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/garecovery/two_of_two.py", line 28, in __init__
    self.is_testnet = self._is_testnet()
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/garecovery/two_of_two.py", line 36, in _is_testnet
    pointer = self.txdata[0]['prevout_pointers'][0]
IndexError: list index out of range

Can you help me?

**Comment by jkauffman1** [comment]
Hi,
Could you please post a listing of the contents of the nlocktimes.zip file by running the following command:
    $ unzip -l nlocktimes.zip
Thanks

**Comment by lewixlabs** [comment]
Hi jkauffman1,
inside the zip file there is this encrypted file:
Archive:  nlocktimes.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
      100  2017-07-31 16:25   nlocktimes.encrypted
---------                     -------
      100                     1 file

Il giorno ven 1 set 2017 alle ore 15:57 jkauffman1 <notifications@github.com>
ha scritto:

**Comment by greenaddress** [comment]
this should be fixed now, closing, feel free to reopen if you have any new issue
